"use client";
import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import { appWithTranslation } from 'next-i18next'
import { I18nextProvider } from 'react-i18next'
import i18n from '../locales/i18n';
import { Provider } from 'react-redux';
import store from '@/redux';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <I18nextProvider i18n={i18n}>
          <Provider store={store}>
            {children}
            <ToastContainer position='bottom-left' />
          </Provider>
        </I18nextProvider>
      </body>
    </html>
  )
}
export default appWithTranslation(RootLayout)